### ISSUE TITLE
service is not working due to http/https 301 error

### ISSUE THREAD

**Issue by dobratzp** [harry-wood/osm-notes-kml#6]
I tried to download some notes as a KML today, and this service failed to generate the KML.

Instead, we get "Notes API responded with code 301" and then the HTTP error result.

I think the issue is that the OSM Notes API no longer responds directly using the http URL and now requires the https URL.

In api.kml.php:
`$API_BASE_URL = 'http://api.openstreetmap.org/api/0.6/notes.json';`

Maybe the fix is as simple as changing this to:
`$API_BASE_URL = 'https://api.openstreetmap.org/api/0.6/notes.json';`

**Comment by harry-wood** [comment]
Ah yes. Thanks for noticing! Good to know people are using it!

That's fixed: https://github.com/harry-wood/osm-notes-kml/commit/e8ee639db19728da08c3167dfd2ed94621563d72
